### ISSUE TITLE
Imports don't work

### ISSUE THREAD

**Issue by edvorg** [yogthos/lein-sass#10]
Need to investigate this problem, it will probably also shed some light on proper source maps format. Currently we manually modify resulting source maps to make it all work.
[Reference](https://github.com/medialize/sass.js/blob/master/docs/api.md#the-importer-callback) to documentation.

**Comment by ghost** [comment]
Fixed by 54070ed50381a50babe57463b35116edec3d625a?

**Comment by ghost** [comment]
Does not actually work. I have a `scss/site.scss` file, [as described in the bootstrap 4.1 documentation](https://getbootstrap.com/docs/4.0/getting-started/theming/), with following content:
```scss
@import "../third_party/bootstrap/scss/bootstrap";
```

This path points to a checkout of [bootstrap](https://github.com/twbs/bootstrap)'s v4.1.3 tag. It does not matter whether I include the `../` or not.

I have this in `project.clj`:
```clj
:plugins [[yogthos/lein-sass "0.1.6"]]
:sass {:source "scss"
       :target "target/public/css"}
```

I get the following error message:
```
$ lein sass
compiling site.scss
Assertion failed: undefined
Assertion failed: undefined
scss/site.scss:null:null failed to compile:
nil
```

**Comment by terjedahl** [comment]
Fixed!

See PR:  https://github.com/yogthos/lein-sass/pull/15

The problem was that the importer callback got a request object where `resolved` could be truncated (missing "resource" in my case):

```
 {"current":"responsive",
  "previous":"../../private/sass/app.scss",
  "resolved":"/private/sass/responsive",
  "path":null,
  "options":null}
 ```

And so in JS custom function `simpleIcludes` `(a == value)` would not match:

```
ARR: 
 resources/private/sass/responsive,
 resources/private/sass/_responsive,
 resources/private/sass/_responsive.scss,
 resources/private/sass/_responsive.sass,
 resources/private/sass/_responsive.css,
 resources/private/sass/responsive.scss,
 resources/private/sass/responsive.sass,
 resources/private/sass/responsive.css  
VALUE: 
 private/sass/responsive
```

The solution was simply to do `if (a.endsWith(value))` .

Also, in the PR:
- Extended pre-processing to strip out single-line comments and to preserve lines.
- Improved error message printout.
- Fixed test.
- Boy-scouting.

**Comment by yogthos** [comment]
Thanks again for the PR! :)

**Comment by ghost** [comment]
@terjedahl Could you explain in more detail, which issue you fixed? And example of code that did not work before and that does work now?

**Comment by terjedahl** [comment]
Sure.  
I have a file `resources/private/sass/app.scss` which has an imports statement, one of which is for `_responsive.scss` in the same directory.
The file is loaded correctly into Sass.js, but when Sass.js resolves the path to `
/private/sass/responsive`.  The custom function `
simpleIcludes` tried to match this with all available options using `==`, which did not succeed.
By matching with `.endsWith` instead, we do get a match and we can respond in the importer callback function with a corrected path.
You can see I left commented-out print statements at line 227 and line 57. 
Hope this helps explain it.
