### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by edvorg** [yogthos/lein-sass#5]
Hi this is awesome library, as it eliminates sass/sassc dependency, but is it possible to generate source maps using sass.js?

**Comment by edvorg** [comment]
According to this http://sass.js.org/ it appears to be supported, so I guess it's just a matter of some additional call to sass.js api in order to generate source maps

**Comment by yogthos** [comment]
Yeah does look like it should be doable. Any chance you'd be up to doing a pr for this? :)

**Comment by yogthos** [comment]
Looks like it should be doable, any chance you'd be up for doing a pr?

**Comment by yogthos** [comment]
Thanks for the PRs, just pushed out `0.1.3` with the updates.
